local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/Revenant", true))()
Library.DefaultColor = Color3.fromRGB(255,0,0)

Library:Notification({
	Text = "Evade hub by 99B8",
	Duration = 6
})
wait(6)


local GUI = loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/aaaa"))()

local UI = GUI:CreateWindow("evade hub v3.0","feito por 99b8 e hacker")

local Home = UI:addPage("Main",1,true,6)

local player = game.Players.LocalPlayer
local playerName = player.Name

Home:addLabel("Welcome " .. playerName, "")


Home:addButton("clip youtube hack",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "copiado";
    })
    setclipboard("https://youtube.com/@evadehub?si=8RUAdGuK5NPfvN9B")
end)

Home:addButton("clip youtube 99b8",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "copiado";
    })
    setclipboard("https://www.youtube.com/@99B8Scriptsofc")
end)

Home:addButton("clip discord",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "copiado";
    })
    setclipboard("https://discord.gg/TJx4htz9Z9")
end)

local hubs = UI:addPage("hubs",1,true,6)

hubs:addButton("tiger hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
    loadstring(game:HttpGet("https://raw.githubusercontent.com/balintTheDevX/Tiger-X-V3/main/Tiger%20X%20its%20Back"))()
end)

hubs:addButton("Multi Scripter X V3",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://raw.githubusercontent.com/GamerScripter/Multi-Scripter-X/main/loader"))()
end)

hubs:addButton("Equinox Hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(("https://pastebin.com/raw/wzB1Qh78"), true))()
end)




local hubs2 = UI:addPage("hubs2",1,true,6)

hubs2:addButton("davi hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(("https://raw.githubusercontent.com/Davicoderliner/davigui/main/Daviguiv2loader.lua"),true))()
end)

hubs2:addButton("game hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://raw.githubusercontent.com/GamerScripter/Game-Hub/main/loader"))()
end)

hubs2:addButton("lndex hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://raw.githubusercontent.com/IndexZHub/Loader/main/Loader"))()
end)

hubs2:addButton("OrangeX Hub V3",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://raw.githubusercontent.com/ImJosh66/OrangeX-Hub-V3-Rel/main/OrangeX%20V3%20Milvan.txt"))()
end)


local games = UI:addPage("games",1,true,6)

games:addButton("all tycoon script",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://freenote.biz/raw/SkG1nrBqE8",true))()
end)

games:addButton("work a pizza place auto farm",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://pastebin.com/raw/xQTtE6D9"))()
end)

games:addButton("brookhaven Imperial hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(("https://raw.githubusercontent.com/Trev0rZ/LoaderM/main/ImperialHub-Working.lua"),true))()
end)

games:addButton("brookhaven SanderXV2.5",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(('https://raw.githubusercontent.com/sXPiterXs1111/SanderXV2.5/main/SanderXV2.5.lua')))()
end)

local games2 = UI:addPage("games2",1,true,6)

games:addButton("eb gui",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(("https://pastebin.com/6jMv9tq6")))()
end)local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/Revenant", true))()
Library.DefaultColor = Color3.fromRGB(255,0,0)

Library:Notification({
	Text = "Evade hub by 99B8",
	Duration = 6
})
wait(6)


local GUI = loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/aaaa"))()

local UI = GUI:CreateWindow("evade hub v3.0","feito por 99b8 e hacker")

local Home = UI:addPage("Main",1,true,6)

local player = game.Players.LocalPlayer
local playerName = player.Name

Home:addLabel("Welcome " .. playerName, "")


Home:addButton("clip youtube hack",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "copiado";
    })
    setclipboard("https://youtube.com/@evadehub?si=8RUAdGuK5NPfvN9B")
end)

Home:addButton("clip youtube 99b8",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "copiado";
    })
    setclipboard("https://www.youtube.com/@99B8Scriptsofc")
end)

Home:addButton("clip discord",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "copiado";
    })
    setclipboard("https://discord.gg/TJx4htz9Z9")
end)

local hubs = UI:addPage("hubs",1,true,6)

hubs:addButton("tiger hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
    loadstring(game:HttpGet("https://raw.githubusercontent.com/balintTheDevX/Tiger-X-V3/main/Tiger%20X%20its%20Back"))()
end)

hubs:addButton("Multi Scripter X V3",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://raw.githubusercontent.com/GamerScripter/Multi-Scripter-X/main/loader"))()
end)

hubs:addButton("Equinox Hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(("https://pastebin.com/raw/wzB1Qh78"), true))()
end)


hubs:addButton("ro chips panel",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Rochips-Panel-15882"))()
end)

hubs:addButton("ghost hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Ghost-hub-16101"))()
end)


local hubs2 = UI:addPage("hubs2",1,true,6)

hubs2:addButton("davi hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(("https://raw.githubusercontent.com/Davicoderliner/davigui/main/Daviguiv2loader.lua"),true))()
end)

hubs2:addButton("game hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://raw.githubusercontent.com/GamerScripter/Game-Hub/main/loader"))()
end)

hubs2:addButton("lndex hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://raw.githubusercontent.com/IndexZHub/Loader/main/Loader"))()
end)

hubs2:addButton("OrangeX Hub V3",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://raw.githubusercontent.com/ImJosh66/OrangeX-Hub-V3-Rel/main/OrangeX%20V3%20Milvan.txt"))()
end)


local games = UI:addPage("games",1,true,6)

games:addButton("all tycoon script",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://freenote.biz/raw/SkG1nrBqE8",true))()
end)

games:addButton("work a pizza place auto farm",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://pastebin.com/raw/xQTtE6D9"))()
end)

games:addButton("brookhaven Imperial hub",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(("https://raw.githubusercontent.com/Trev0rZ/LoaderM/main/ImperialHub-Working.lua"),true))()
end)

games:addButton("brookhaven SanderXV2.5",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(('https://raw.githubusercontent.com/sXPiterXs1111/SanderXV2.5/main/SanderXV2.5.lua')))()
end)

local games2 = UI:addPage("games2",1,true,6)

games2:addButton("eb gui",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(('https://pastebin.com/raw/XstKr68q')))()
end)

games2:addButton("batalha de slap",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://rawscripts.net/raw/GUIDE-Slap-Battles-GFET-Hub-OP-16064"))()
end)


local admin = UI:addPage("admin",1,true,6)

admin:addButton("ShatterVast Admin",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(('https://pastebin.com/raw/m66HEHFu')))()
end)

admin:addButton("Infnite yield",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(('https://pastebin.com/raw/KtyqgNCD')))()
end)



admin:addButton("cmd-x",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://raw.githubusercontent.com/CMD-X/CMD-X/master/Source",true))()
end)



admin:addButton("fates admin",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet("https://raw.githubusercontent.com/fatesc/fates-admin/main/main.lua"))();
end)

admin:addButton("reviz admin",function()
    game.StarterGui:SetCore("SendNotification",{
        Title = "pronto";
        Text = "executado";
    })
loadstring(game:HttpGet(('https://pastebin.com/raw/pyzjWNhk'),true))()
end)
